# Quality Gates Configuration for Vine Project
# This file defines the quality thresholds that must be met for CI/CD to pass

quality_gates:
  # Test Coverage
  coverage:
    minimum_percentage: 80
    fail_under: true

  # Code Complexity (Xenon)
  complexity:
    max_absolute: "B"      # No function should exceed B complexity
    max_average: "A"       # Average complexity should be A or better
    max_modules: "A"       # Module-level complexity should be A or better

  # Dead Code Detection (Vulture)
  dead_code:
    min_confidence: 80     # Minimum confidence level for dead code detection

  # Security
  security:
    audit_dependencies: true
    fail_on_vulnerabilities: true

  # Documentation
  documentation:
    build_required: true
    link_check_required: false  # Optional: can be enabled later

  # Type Safety
  type_safety:
    strict_mode: true
    fail_on_any_errors: true

  # Linting
  linting:
    fail_on_unfixable: true
    auto_fix_enabled: true

# Quality Gate Enforcement
enforcement:
  # Which gates are required for different events
  pull_request:
    - coverage
    - complexity
    - type_safety
    - linting
    - security

  push_to_main:
    - coverage
    - complexity
    - type_safety
    - linting
    - security
    - documentation

  release:
    - coverage
    - complexity
    - type_safety
    - linting
    - security
    - documentation
    - dead_code

# Reporting
reporting:
  generate_summary: true
  upload_coverage: true
  notify_on_failure: false  # Can be enabled for Slack/Discord notifications
