name: CI (nox)

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        mode: [minimal, full]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv + nox
        run: |
          pip install --quiet uv
          uv pip install --quiet 'nox>=2024.4.15'

      - name: Run nox sessions
        run: |
          # Run the test suite for every matrix cell
          nox -s tests -- --mode=${{ matrix.mode }}

      - name: Run quality gates
        if: ${{ matrix.python-version == '3.11' && matrix.mode == 'full' }}
        run: |
          nox -s lint type_check docs complexity security

      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.11' && matrix.mode == 'full' }}
        uses: codecov/codecov-action@v4
