name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', '.github/workflows/docs.yml' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Sphinx and dependencies
        run: |
          uv pip install sphinx sphinx-rtd-theme myst-parser furo sphinx-autodoc-typehints sphinx-copybutton

      - name: Build Sphinx docs
        run: |
          cd docs
          make html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
